project:
  type: website
  output-dir: docs

website:
  title: "Anup Phayal"
  navbar:
    right:
      - href: index.qmd
        text: About
      - Research.qmd
      - Teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

