# Change 'comments' to true for Disqus comments
title:  Anup Phayal
tagline:  
author:
  name: 'Anup'
  twitter:  sky_nova

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ' '

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: 'UA-112060364-1'

menu:
- {name: 'Home', url: '..'}
- {name: 'Research', url: 'research.html'}
- {name: 'Teaching', url: 'teaching.html'}
- {name: 'Vitae', url: '../files/cv_anup_phayal_current.pdf'}
#- {name: 'Links', url: 'links.html'}
#- {name: 'Contact', url: 'contact.html'}

social:
#- {icon: 'github', link: 'https://www.github.com/seonghuilee'}
- {icon: 'university', link: 'https://uncw.edu/pia/about/facstaff.html'}
#- {icon: 'twitter', link: 'https://twitter.com/sky_nova'}
- {icon: 'envelope', link: 'mailto:phayala@uncw.edu'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer (http://fontawesome.io/icons/)
